### ISSUE TITLE
配列＋forループの組み合わせ

### ISSUE THREAD

**Issue by YoshinoriKobayashi** [CodeCandySchool/ArrayLesson_azusa#1]
@goazle 

とてもよくできていますね！

この課題では、配列がメインなので、forについては触れていないのですが、Swiftの場合は、「配列＋forループ」は次のようにすっきり書くことができます。

```
// 1〜3までの数字を配列で管理をして宣言
let numberArray = [1, 2, 3]
// インデックスで要素を取り出してprintで出力
for num in numberArray {
    print(num)
}
```

よい機会ですので、上記のfor文のように修正してpushしてみてください🙋‍♂️

**Comment by goazle** [comment]
なるほど！[対応してみました](https://github.com/CodeCandySchool/ArrayLesson_azusa/commit/5319239724a4c70c4dba1b8949006b83e509148a)。
ご確認、よろしくお願いします！

**Comment by YoshinoriKobayashi** [comment]
@goazle 
とてもいいですね！

次の課題に進みましょう！
